### ISSUE TITLE
Webservices and custom Sender ID's

### ISSUE THREAD

**Issue by hmalekib** [antonraharja/playSMS#252]
Hello:

We are trying to setup the webservices so users can send SMS messages from any of the authorized sender ID's associated with a users account.
I find that unless you assign a default sender id, the following URL will not work.

https://sms.my-url.net/index.php?app=ws&u=tikaaatel&h=e96861343244234841306acefda44aea8d67a4424324be&op=pv&to=4160000000&msg=test+only

We even tried to add a "from=" but still no luck:

https://sms.my-url.net/index.php?app=ws&u=tikaaatel&h=e96861343244234841306acefda44aea8d67a4424324be&op=pv&from=4161222222&to=4160000000&msg=test+only

The first URL only works when we specify the sender ID in the portal.
What we would like to do is not set a default sender ID and allow SMS messages form any sender ID (the sender ID needs to be specified in the URL..)

**Comment by antonraharja** [comment]
currently sender ID must be set by user through user config

**Comment by antonraharja** [comment]
will be solved in #431, closing this one
