### ISSUE TITLE
strlen() get wrong message length  in arabic and unicode messages

### ISSUE THREAD

**Issue by mshanak** [antonraharja/playSMS#337]
hello , 
 File: sendsms/fn.php 
instead of using strlen() function replace it with mb_strlen() in the following line: 

```
list($count, $rate, $charge) = rate_getcharges(mb_strlen($message . $c_sms_footer,'UTF-8'), $unicode, $c_sms_to);

```

**Comment by antonraharja** [comment]
can you tell me how to reproduce the issue so that I can test this ? also can you copy-paste some log entries telling us that the string length was incorrect, thanks.

anton

**Comment by mshanak** [comment]
hello anton . 
the problem is when i send a uff-8 text ( arabic + Hebrew) with 64 char's the interface ( javascript ) show the relal length ( 64 chars )  but the system (PHP ) Deducted 3 messages .

** this is  a test code : **

```
<?php 
// the $message says "hello" in arabic 
// the message length is : 5 chars
$message="مرحبا";
echo "strlen : ".strlen($message); // output : 10
echo "<br/>mb_strlen : ".mb_strlen($message,'UTF-8'); // output: 5
?>
```

## to fix it : 
file : //sendsms/fn.php ( line 641)
replace the strlen() with mb_strlen(variable,'utf-8') 	
```
list($count, $rate, $charge) = rate_getcharges(mb_strlen($message . $c_sms_footer,'UTF-8'), $unicode, $c_sms_to);
```

**Comment by antonraharja** [comment]
what we want is actually to count them as 10 chars, unicodes are considered taking 2 chars

**Comment by mshanak** [comment]
message lengths : 

normal = 160 char' s
utf-8 = 74 char's

so when the the user send a message with 70 characters he will pay for 1 message ( not 2 ) .

* when using strlen() , the system now show a message  the user will pay for 2 messages  .

**Comment by antonraharja** [comment]
yes, correct, what we want is to get users to pay 2 SMS for unicode message that is more than 70 chars, because that is how most providers charged the sender

**Comment by mshanak** [comment]
ok :+1: 

can you add a  #NAME# , #NUM# buttons in the sendsms interface in the next version ? 
i already added them , 

![screen shot 2015-01-30 at 7 09 44 pm](https://cloud.githubusercontent.com/assets/964266/5980265/82c95ffe-a8b7-11e4-90e3-d445877fabe6.png)




add this attributes to the page html 

```html
<a href="#" onclick="insertAtCaret('message','#NAME#');return false;">#NAME#</a>
<a href="#" onclick="insertAtCaret('message','#NUM#');return false;">#NUM#</a>
```

then add the following to script area :
```javascript
function insertAtCaret(areaId,text) {
    var txtarea = document.getElementById(areaId);
    var scrollPos = txtarea.scrollTop;
    var strPos = 0;
    var br = ((txtarea.selectionStart || txtarea.selectionStart == '0') ? 
        "ff" : (document.selection ? "ie" : false ) );
    if (br == "ie") { 
        txtarea.focus();
        var range = document.selection.createRange();
        range.moveStart ('character', -txtarea.value.length);
        strPos = range.text.length;
    }
    else if (br == "ff") strPos = txtarea.selectionStart;

    var front = (txtarea.value).substring(0,strPos);  
    var back = (txtarea.value).substring(strPos,txtarea.value.length); 
    txtarea.value=front+text+back;
    strPos = strPos + text.length;
    if (br == "ie") { 
        txtarea.focus();
        var range = document.selection.createRange();
        range.moveStart ('character', -txtarea.value.length);
        range.moveStart ('character', strPos);
        range.moveEnd ('character', 0);
        range.select();
    }
    else if (br == "ff") {
        txtarea.selectionStart = strPos;
        txtarea.selectionEnd = strPos;
        txtarea.focus();
    }
    txtarea.scrollTop = scrollPos;
}

```
