### ISSUE TITLE
sms rate per user

### ISSUE THREAD

**Issue by mshanak** [antonraharja/playSMS#341]
hello,
i wold like if we can have an sms rate per-user  for each prefix in the next version . 

i made these change in the current version .

![screen shot 2015-01-31 at 5 41 36 pm](https://cloud.githubusercontent.com/assets/964266/5988626/eed17b3c-a970-11e4-84b2-4739987a6e2d.png)

**Comment by antonraharja** [comment]
you meant you already done this ? can you please share your changes, thanks.

**Comment by antonraharja** [comment]
dup #150
