### ISSUE TITLE
sms rate value accept 4 or 5 decimal digits

### ISSUE THREAD

**Issue by mshanak** [antonraharja/playSMS#342]
hello 
playSMS currently  can accept a 4 decimal  number ( ex : 0.123) . 
but in sum cases we need to have 4 or 5 decimal  (ex : 0.12345) .
can you consider this issue in the next version ? 

![screen shot 2015-01-31 at 5 46 24 pm](https://cloud.githubusercontent.com/assets/964266/5988662/3f2ead60-a972-11e4-90ed-4fbe01414951.png)

```
ALTER TABLE `playsms_featureSimplerate` CHANGE `rate` `rate` DECIMAL(13,4) NOT NULL DEFAULT '0.00000';
```

**Comment by antonraharja** [comment]
hi, no I wont change this, it wont stop, it was 3 now 4, then 5? :D

anton
