### ISSUE TITLE
very slow phonebook with 15,000 contacts

### ISSUE THREAD

**Issue by mshanak** [antonraharja/playSMS#343]
<h2>The Problem </h2>
after using playsms for 5 months , our clients start to import large number of contacts to there phonebook , but unfortunately with this large number of contacts  the phoneBook became very slow (mor than 20 seconds for each request ) because the SQL statement use LEFT JOIN with other tables  which is not efficiently supported in mysql  . 
 
<h2>Fix it</h2>
To go over this problem , you need to make indexes for the following attributes 

DBTable | Fields to index
------------ | -------------
playsms_featurePhonebook |  uid,mobile
playsms_featurePhonebook_group |  uid,code,flag_sender
playsms_featurePhonebook_group_contacts | gpid ,pid

**Comment by antonraharja** [comment]
if you can pull request for the updated playsms.sql that'll be great, but if not then I can do that, thanks

**Comment by antonraharja** [comment]
Hi,

Is this correct:
https://github.com/antonraharja/playSMS/commit/1826ed36d6d8599fe4ad791eed87dfc4338603e6

anton

**Comment by mshanak** [comment]
``` sql
ALTER TABLE `playsms_featurePhonebook` ADD INDEX ( `uid` ) ;
ALTER TABLE `playsms_featurePhonebook` ADD INDEX ( `mobile` ) ;

ALTER TABLE `playsms_featurePhonebook_group` ADD INDEX ( `uid` ) ;
ALTER TABLE `playsms_featurePhonebook_group` ADD INDEX ( `flag_sender` ) ;
ALTER TABLE `playsms_featurePhonebook_group` ADD INDEX ( `code` ) ;


ALTER TABLE `playsms_featurePhonebook_group_contacts` ADD INDEX ( `gpid` ) ;
ALTER TABLE `playsms_featurePhonebook_group_contacts` ADD INDEX ( `pid` ) ;

```
