### ISSUE TITLE
jscss/jquery/jquery-2.0.3.min.js ::: No such file or directory

### ISSUE THREAD

**Issue by aristide** [antonraharja/playSMS#346]
Hi @antonraharja. I ran playsms 1.0-rc4 and everything is quite ok. I'm just having an error on my nginx log file, telling me that:: 
```
plugin/themes/common/jscss/jquery/jquery-2.0.3.min.js" failed (2: No such file or directory)
``` 
it's comming from 
```
./web/plugin/core/sendsms/templates/sendsms.html:2:	src="{{ HTTP_PATH_THEMES }}/common/jscss/jquery/jquery-2.0.3.min.js"></script>
```
On my local src, i just :
 - removed **jquery** from script **src** 
 - replaced **jquery-2.0.3.min.js** with **jquery.min.js**

**Comment by antonraharja** [comment]
please use the master version, this has been fixed in commit https://github.com/antonraharja/playSMS/commit/93dcce5ca25a6a9308eaf42c497b8a0ffbb42b2e

you can simply remove loading jquery from sendsms.html

anton
