### ISSUE TITLE
Schedule option in Send message page is not working

### ISSUE THREAD

**Issue by antonraharja** [antonraharja/playSMS#347]
Scheduled SMS is sent right away, even when you scheduled way past a day (no timezone issue)

ref:
https://groups.google.com/d/msg/playsmsusergroup/baNU-yH1YPo/4zYDFZt5bx8J

**Comment by andyspb2019** [comment]
Scheduling a date/time to send message does not work corectly. I set my time to send but message unreadable from my smartphone. Encoding of message is Cyrillic. Message with latin encoding work perfectly.

playSMS version 1.4.2 + smstools 3.1.21
