### ISSUE TITLE
Unable to send messages when clickatell password contains &

### ISSUE THREAD

**Issue by fbonzon** [antonraharja/playSMS#385]
If your clickatell password contains the & character, playSMS can't send messages with this gateway.

Actual:
- When character & is entered by user inside the password field, it is stored in the database as &amp;amp;

Expected:
- When character & is entered by user inside the password field, it is stored in the database as %26 using urlencode()

**Comment by antonraharja** [comment]
or, when posting to clickatell using urlencode for password, please test.

https://github.com/antonraharja/playSMS/blob/master/web/plugin/gateway/clickatell/fn.php
line 96 and 149

**Comment by fbonzon** [comment]
Correct, it would work. I agree it's best to store the password without any encoding in the database, and use urlencode() whenever building the query string for clickatell.

However, this doesn't fix the bug. E.g. this password entered by user:

```
< > &
```

is stored in DB as:

```
&lt; &gt; &amp;
```

The password should not be converted with htmlspecialchars() before written in the DB. Same problem occurs for other fields, such as `additional_param` which is stored in the DB and sent to clickatell as `deliv_ack=1&amp;callback=3`.

**Comment by antonraharja** [comment]
oh I didn't see it in my email (forwarded by Github) that it was stored as &amp; :) ok

**Comment by antonraharja** [comment]
Would you mind to check this for me, lib/fn_core.php core_sanitize_input(), the htmlpurifier most likely the cause of this, could you comment it and try to save a password containing `&`

If it is, for now I won't change core_sanitize_input() but probably will find another way to workaround this

**Comment by fbonzon** [comment]
I confirm it is due to htmlpurifier. If I comment out this line:
https://github.com/antonraharja/playSMS/blob/1c54d6e9b107ca35c1442e5a03b68051fbd55d39/web/init.php#L147
then the password is stored correctly.
htmlpurifier is useful though to display back values in the browser, and should not simply be removed.

**Comment by antonraharja** [comment]
alright then, we will deal with this case by case, in this issue the clickatell password will need to be htmlspecialchars_decode() first then urlencode() before submitted to clickatell

its possible other gateway that is working via HTTP API also need to be changed
