### ISSUE TITLE
Subusers don't use parent outgoing smsc

### ISSUE THREAD

**Issue by tapule** [antonraharja/playSMS#392]
If you have an Admin with a default smsc, and in this admin you have a User with its own smsc, if you add sub-users to this user, the logic say that these sub-users sould use the parent smsc but this doesn't work and the sub-users get the Admin smsc ignoring the direct parent configuration.

As you can't config an outgoing route for sub-users, I tend to think that a sub-user must use the outgoing route configured in its parent.

**Comment by antonraharja** [comment]
subusers routes will follow their parents
