### ISSUE TITLE
Reports shows gateway names instead of smsc name

### ISSUE THREAD

**Issue by tapule** [antonraharja/playSMS#395]
Hi,
Since this commit: https://github.com/antonraharja/playSMS/commit/000a99cb125b7464fc04e75f0c6e90f72e1c378d
there are some reports where the column "SMSC" shown the gateway name instead of the smsc name.
For example in Admin->Reports->All sent messages.

Greetings.

**Comment by antonraharja** [comment]
it should be smsc, not gateway

anton
