### ISSUE TITLE
Problem encoding Unicode (Arabic / Hebrew)

### ISSUE THREAD

**Issue by yosef454** [antonraharja/playSMS#400]
Hello,

There is a problem with sending SMS in Arabic / Hebrew.
It comes as: ??????
version is 1.0-rc7.
I tried to play a bit with encoding (fn.php)and could not solve the problem.
I use a nexmo.

Thank you.

**Comment by antonraharja** [comment]
when you typed your message (from My account -> Compose message), did you saw that the Unicode option (checkbox) checked ? Please try again and watch the unicode option (checkbox) checked automatically

**Comment by yosef454** [comment]
Yes.
When I start to type Unicode message box automatically selected.
It still sends ?????

**Comment by yosef454** [comment]
Yes.
When I start to type Unicode message box automatically checked.
It still sends ?????

**Comment by antonraharja** [comment]
waiting others to confirm this issue

**Comment by luckycreationsindia** [comment]
It's working perfectly fine when I tried with Hindi and Arabic language.... No issues found from my side... Maybe some other issue...

By the way I'm using kannel...

**Comment by antonraharja** [comment]
me too. probably on the nexmo gateway, or nexmo side. still, need feedbacks

**Comment by luckycreationsindia** [comment]
Nexmo - fn.php - Line 59

I think it must be UTF-8 instead of UCS-2 as per the Nexmo Docs.

**Comment by antonraharja** [comment]
ok, please test:

edit plugin/gateway/nexmo/fn.php line 59

from:
`$sms_msg = mb_convert_encoding($sms_msg, "UCS-2", "auto");`

to:
`$sms_msg = mb_convert_encoding($sms_msg, "UTF-8", "auto");`

restart playsmsd and then send 1 unicode SMS via nexmo

**Comment by yosef454** [comment]
Change from UCS-2 to UFT-8.
Not solve the problem.

**Comment by antonraharja** [comment]
I've tested on my server, I changed encoding from UCS-2 to UTF-8, and remove wrong code on line 55

check this commit and make changes accordingly on your server:
https://github.com/antonraharja/playSMS/commit/40d96b08b9edf79883cc0082aa6eda01c68832f8

**Comment by MajidHws** [comment]
where does the file locate?
