### ISSUE TITLE
Possible bug in Compose message interface

### ISSUE THREAD

**Issue by tapule** [antonraharja/playSMS#409]
In "Compose message" interface, if you put @ or # in the "Send to" box, you can see all the user in the system, not only yours.
For example, in a subuser, if I put "@a", the dropdown list shows me all the users in the system whose name includes "a", so I can see user names from other accounts.

I think that this can be a dangerous privacity problem.

Greetings.

**Comment by antonraharja** [comment]
yes, I'm aware of this, and have some plan about this including buddy system or contact list (like messenger contact list, etc..), but that would take quite sometime to build, at least not for now

what is your suggestion, so that this privacy things can be at least minimize for upcoming release

**Comment by tapule** [comment]
I think that can be enough if you limit this list to the current account users, ie, show only user names that are owned by the current account.

**Comment by antonraharja** [comment]
how about from subusers ?

anton

**Comment by luckycreationsindia** [comment]
I don't know but I can't see any other users than the member of the user. It might be issue with group (Share phonebook and allow broadcast) - Select Me Only to hide from all other users.

Cross Checked with Users and Subusers.

Only Admin can see other users.

**Comment by tapule** [comment]
This is from a subuser with an empty phonebook:
![snap00](https://cloud.githubusercontent.com/assets/3315610/7134533/004edb50-e29e-11e4-8b36-9c7806096df1.png)

If I go to compose message it shows me all the users from other subuser, user and admin:
![snap01](https://cloud.githubusercontent.com/assets/3315610/7134543/167f544a-e29e-11e4-90e5-3d0cb4ccbfe2.png)

Anton, yes, I think that this can be valid, but don't forget that in this case a "user" not only can access other users and subusers phonebooks but also admins phonebooks.

**Comment by antonraharja** [comment]
which version do you use ?

I remembered I did something about that, but I haven't check that again.

anton

**Comment by tapule** [comment]
If I'm not wrong it is playSMS version 1.0-master Release date 150309
Is there any way to see it?

**Comment by antonraharja** [comment]
here (on March 15th):
https://github.com/antonraharja/playSMS/commit/cf0e7a5da7c5b14fddcd624e548d527377d84d5f

playSMS will only display usernames that is already added in phonebook

anton

**Comment by tapule** [comment]
Wow!!.
As I see, I need to upgrade to the current master. Anyway I will try to patch that file.
Sorry for this waste of time Anton and thank you for your effort and your dedication to PlaySms.

Greetings.

**Comment by antonraharja** [comment]
correction

playSMS will display only usernames where their mobile numbers are added in phonebook

- User `aaaa` have mobile `0987654321`
- User `bbbb` will have to add mobile number `0987654321` to its phonebook so that playSMS resolve `@aaaa`

**Comment by tapule** [comment]
So cf0e7a5 is not the fix to the problem I say?

**Comment by antonraharja** [comment]
when you update to master version then when you type @a you will not see any other usernames

playSMS will only display usernames which their mobile numbers already added by you in your phonebook

anton

**Comment by tapule** [comment]
Thank you Anton
