### ISSUE TITLE
[Bug] Subuser Credit

### ISSUE THREAD

**Issue by luckycreationsindia** [antonraharja/playSMS#410]
Hi,

When a User add credit to subuser It can add beyond it's credit limit.

Administrator(Unlimited Credit) > User(500 Credit) > Subuser(5000 Credit)

If User has given 500 credits and If he creates subuser and add credit of 5000 It's credited instead of showing error or warning.

I don't know If it's purposely built like this but this might create serious issue for Admin in billing.

**Comment by antonraharja** [comment]
Its purposely built like that.

Example:

- A is user
- B is subuser's of A
- admin add 500 to A then A have 500 credits
- A add 8000 to B then B have 8000 credits
- when B sent 1 SMS that took 2 credits then A will be deducted as well
- so, when B sent 1 SMS
- B deducted 2 credits
- at the same time A also deducted 2 credits
- B balance now 7998
- A balance now 498

this is what some people called "overselling"

user type accounts are designed as reseller
subuser type accounts are designed as client's of reseller

**Comment by luckycreationsindia** [comment]
Ohh now I got it. Thanks... :-)
