### ISSUE TITLE
Security issue with manage sender ID page

### ISSUE THREAD

**Issue by yahia007** [antonraharja/playSMS#428]
User can access Sender ID Management Page without being authorized.

It won't show any records but he still can access it without redirecting to login page.

try:
http://playsms.org/trial/index.php?app=main&inc=core_sender_id&op=sender_id_list

**Comment by antonraharja** [comment]
"Manage sender ID" menu is for everyone. Please discuss this in user forum instead.

**Comment by yahia007** [comment]
I mean any one, even if he is not a user in the system.

Try access the URL while you are logged out.

It will show the page without headers and footers.

**Comment by antonraharja** [comment]
ah ic, you're right
