### ISSUE TITLE
FATAL ERROR : Unable to find composer files

### ISSUE THREAD

**Issue by Mmazarei** [antonraharja/playSMS#446]
i'm try install playsms on raspberry pi.
befor install this, install php 5.5 and mysql 5.6 and nginx Web Server
i'm use install shell Script but in web and playsmsd ckeck get error 'FATAL ERROR : Unable to find composer files Please run composer.phar update'.
i'm run this  command get 
'Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files'
how to fix this

**Comment by antonraharja** [comment]
this is not a bug, please consult in user forum

anton
