### ISSUE TITLE
Gammu SMS Delivery Report not working..

### ISSUE THREAD

**Issue by 88ee55** [antonraharja/playSMS#448]
192.168.1.68 192.168.1.152 2015-05-21 14:14:07 PID555da1de90112 admin L2 sendsms # start uid:1 sender_id:[] smsc:[]
192.168.1.68 192.168.1.152 2015-05-21 14:14:07 PID555da1de90112 admin L2 sendsms_queue_create # saving queue_code:c5a86f977ab3def20cdf937adc1b53ef src: scheduled:2015-05-21 14:14:07
192.168.1.68 192.168.1.152 2015-05-21 14:14:07 PID555da1de90112 admin L2 sendsms_queue_create # saved queue_code:c5a86f977ab3def20cdf937adc1b53ef id:8
192.168.1.68 192.168.1.152 2015-05-21 14:14:07 PID555da1de90112 admin L2 sendsms # dst:1 sms_count:1 total_charges:0
192.168.1.68 192.168.1.152 2015-05-21 14:14:07 PID555da1de90112 admin L2 sendsms_queue_push # saving queue_code:c5a86f977ab3def20cdf937adc1b53ef dst:+7922222222
192.168.1.68 192.168.1.152 2015-05-21 14:14:07 PID555da1de90112 admin L2 sendsms_queue_push # saved queue_code:c5a86f977ab3def20cdf937adc1b53ef smslog_id:14
192.168.1.68 192.168.1.152 2015-05-21 14:14:07 PID555da1de90112 admin L2 sendsms # end queue_code:c5a86f977ab3def20cdf937adc1b53ef queue_count:1 sms_count:1 failed_queue:0 failed_sms:0
- - 2015-05-21 14:14:08 PID555da1e06f902 - L2 sendsmsd # start processing queue_code:c5a86f977ab3def20cdf937adc1b53ef queue_count:1 sms_count:1 scheduled:2015-05-21 14:14:07 uid:1 gpid:0 sender_id:
- - 2015-05-21 14:14:08 PID555da1e06f902 - L2 sendsmsd # sending queue_code:c5a86f977ab3def20cdf937adc1b53ef smslog_id:14 to:+7922222222 sms_count:1 counter:1
- - 2015-05-21 14:14:08 PID555da1e06f902 - L2 sendsms_process # start
- - 2015-05-21 14:14:08 PID555da1e06f902 - L2 simplerate__cansend # allowed user uid:1 sms_to:+7922222222 credit:0.000 count:1 rate: charge:0 balance:0
- - 2015-05-21 14:14:08 PID555da1e06f902 - L2 sendsms # saving smslog_id:14 u:1 g:0 gw:gammu smsc:gammu s: d:+7922222222 type:text unicode:1 status:0
- - 2015-05-21 14:14:08 PID555da1e06f902 - L2 sendsms_process # saved smslog_id:14 id:14
- - 2015-05-21 14:14:08 PID555da1e06f902 - L2 gammu__outgoing # saving outfile:/var/spool/gammu/outbox/OUTA20150521_141408_00_+7922222222_14100011100010.txt
- - 2015-05-21 14:14:08 PID555da1e06f902 - L2 gammu__outgoing # saved outfile:/var/spool/gammu/outbox/OUTA20150521_141408_00_+7922222222_14100011100010.txt
- - 2015-05-21 14:14:08 PID555da1e06f902 - L2 simplerate__deduct # enter smslog_id:14
- - 2015-05-21 14:14:08 PID555da1e06f902 - L2 credit_hook_rate_setusercredit # no changes uid:1 balance:0
- - 2015-05-21 14:14:08 PID555da1e06f902 - L2 simplerate__deduct # user uid:1 parent_uid: smslog_id:14 msglen:14 count:1 rate: charge:0 credit:0.000 balance:0
- - 2015-05-21 14:14:08 PID555da1e06f902 - L2 simplebilling__post # saving smslog_id:14 rate: credit:0.000 count:1 charge:0
- - 2015-05-21 14:14:08 PID555da1e06f902 - L2 simplebilling__post # saved smslog_id:14 id:14
- - 2015-05-21 14:14:08 PID555da1e06f902 - L2 sendsms_process # end
- - 2015-05-21 14:14:08 PID555da1e06f902 - L2 sendsmsd # result queue_code:c5a86f977ab3def20cdf937adc1b53ef to:+7922222222 flag:1 smslog_id:14
- - 2015-05-21 14:14:09 PID555da1e06f902 - L2 sendsmsd # finish processing queue_code:c5a86f977ab3def20cdf937adc1b53ef uid:1 sender_id: queue_count:1 sms_count:1
- - 2015-05-21 14:14:42 PID555d96e00b641 - L2 gammu__getsmsstatus # smslog_id:14 unlink the_fn:/var/spool/gammu/sent/OUTA20150521_141408_00_+7922222222_14100011100010.txt p_status:1
- - 2015-05-21 14:14:43 PID555d96e00b641 - L2 simplebilling__finalize # saving smslog_id:14
- - 2015-05-21 14:14:43 PID555d96e00b641 - L2 simplebilling__finalize # saved smslog_id:14
- - 2015-05-21 14:14:49 PID555d96e015ac6 - L2 recvsms_inbox_add # saving sender:+7922222222 receiver: target:admin reference_id:
- - 2015-05-21 14:14:49 PID555d96e015ac6 - L2 recvsms_inbox_add # saved id:18 sender:+7922222222 receiver: target:admin

**Comment by antonraharja** [comment]
supports questions in user forum, not here.
