### ISSUE TITLE
My sent messages export encoding

### ISSUE THREAD

**Issue by yosef454** [antonraharja/playSMS#450]
When I make exports from My sent messages
If there are messages in Hebrew, they appear CSV file gibberish

**Comment by antonraharja** [comment]
which playSMS version ? if not 1.0 then please update to 1.0

**Comment by yosef454** [comment]
version 1.0

**Comment by antonraharja** [comment]
when you said "they appeared gibberish" how did you read it ? using excel ?

can you provide example CSV file ? you can send the file to my email: antonrd@gmail.com

**Comment by yosef454** [comment]
I use Excel.

**Comment by yosef454** [comment]
I use Excel.
I sent you an example.

**Comment by antonraharja** [comment]
It read ok in LibreOffice and also in Gmail preview. When you open with Excel, try looking for option to set encoding to UTF-8

**Comment by antonraharja** [comment]
ref: http://answers.microsoft.com/en-us/office/forum/office_2013_release-excel/how-to-open-csv-file-of-hebrew-language/8963c913-fb3d-4f22-866e-d373366ba196

Text wizard screenshot

**Comment by yosef454** [comment]
Uncomfortable every time you do a report to make the whole process

**Comment by yosef454** [comment]
Another problem Send from file.
If a file to an in Hebrew it does not send the message.
I converted file  to UTF8 with notepad ++, it sent a blank message.

**Comment by antonraharja** [comment]
ok.

dup #304
