### ISSUE TITLE
support for gammu with mysql backend

### ISSUE THREAD

**Issue by codemonkeyforever** [antonraharja/playSMS#452]
Hello,

I am using gammu with the mysql backend and now heard of playsms as the best web frontend for it, also supporting an android app for sending sms over there. Thus, I tried to install playsms on my server, the installation also worked like a charm, however, the interconnection between gammu and playsms does not work so far. I noticed that playsms uses the file backend of gammu in the according install guide, and found no information on how to use it with the mysql backend. Is it supported yet?

Best wishes, have a nice day,

Josef

**Comment by antonraharja** [comment]
Hi,

At the moment it is not supported.

Please continue the discussion in playSMS Forum.

anton

**Comment by tenzap** [comment]
Forums is presently unreachable see #636 
Is there any plan to support gammu-smsd database backends (mysql, postgresql...). That would be great.
