### ISSUE TITLE
./plugin/gateway/clickatell/callback.php | code error

### ISSUE THREAD

**Issue by rmarinier** [antonraharja/playSMS#455]
Dear all,

i'v found a mistake in file ./plugin/gateway/clickatell/callback.php
line 11 : ...['libs']... must me 'lib'
correct with : 
include $core_config['apps_path']['lib'] . "/function.php";

Regards

**Comment by antonraharja** [comment]
no, the correct one is `$core_config['apps_path']['libs']`

**Comment by antonraharja** [comment]
oh I forgot to ask, what version are you using ? if not 1.0 please upgrade to 1.0

anton

**Comment by rmarinier** [comment]
Version 1.0 (https://github.com/antonraharja/playSMS)
In config file, lib is cleary in path (not libs).

Regards

**Comment by antonraharja** [comment]
which config file ?

see this file:
https://github.com/antonraharja/playSMS/blob/master/web/init.php

line 83

**Comment by rmarinier** [comment]
Ok! But why since i changed 'libs' to 'lib': i receive callback from clickatell? (instead to 'libs' : does'nt works)

**Comment by antonraharja** [comment]
that is another issue, I'm closing this one

**Comment by rmarinier** [comment]
update: I've found the "bug". It's due to my conf in my Ubuntu serv. libs and lib rep are supervised by a a security system. libs works well right now.
Sorry for the issue.
