### ISSUE TITLE
Write a message with ISO-8859-1 chars

### ISSUE THREAD

**Issue by rmarinier** [antonraharja/playSMS#457]
Dear all,
I've an issue when i send message with accentued words (Clickatell gateway).
ie. in french: Hôtel / Déjeuner / L'entreprise / Noël / évènement / ... é à è ç ù ö 

If i send évènement, 
When received on phone, that became: AcvA"nement.

Any idea to fix-it ?

Regards

**Comment by antonraharja** [comment]
![see this screenshot](https://lh3.googleusercontent.com/6dqeuRL0TrgS5xBL9OVJXyabZu-AXMQnefGdf7PEbpk=w602-h591-no)

in my test the unicode checkbox is automatically checked

and in my log I saw this:

```
- - 2015-06-15 06:17:37 PID557e0b91c8141 - L3 sendsms # final smslog_id:10 gw:clickatell smsc:clickatell message:Hôtel / Déjeuner / L'entreprise / Noël / évènement / ... é à è ç ù ö @admin len:87
- - 2015-06-15 06:17:37 PID557e0b91c8141 - L3 clickatell_hook_sendsms # enter smsc:clickatell smslog_id:10 uid:1 to:123456789
- - 2015-06-15 06:17:37 PID557e0b91c8141 - L3 clickatell__outgoing # url:https://api.clickatell.com/http/sendmsg?api_id=123456&user=playsms&password=playsms&to=123456789&msg_type=SMS_TEXT&text=004800f400740065006c0020002f0020004400e9006a00650075006e006500720020002f0020004c00270065006e007400720065007000720069007300650020002f0020004e006f00eb006c0020002f002000e9007600e8006e0065006d0065006e00740020002f0020002e002e002e002000e9002000e0002000e8002000e7002000f9002000f60020004000610064006d0069006e&unicode=1&from=TESTSENDER&deliv_ack=1&callback=3
```

what's important is: `unicode=1` and the `test` has lots of 00 like above example

please check yours, when testing again

**Comment by rmarinier** [comment]
Thanks for your reply and support.
It's impossible to check Unicode message in my conf. And i don't really know why. When i try to check, that's inoperate.

**Comment by antonraharja** [comment]
You need to just type your characters and it should be autochecked, you can't click the checkbox.

Try to paste this in message field:

`Hôtel / Déjeuner / L'entreprise / Noël / évènement / ... é à è ç ù ö`

Tell us if your unicode checkbox checked automatically or not.

anton

**Comment by rmarinier** [comment]
2 cases:
- When i paste: Hôtel / Déjeuner / L'entreprise / Noël / évènement / ... é à è ç ù ö  : That works !
- When i try: évènement  the box did'nt check!

**Comment by antonraharja** [comment]
according to https://en.wikipedia.org/wiki/GSM_03.38 `é` and `è` in `évènement` are not unicode

try to ask Clickatell, do we need `unicode=1` in submit url or any other useful advice form them

anton

**Comment by rmarinier** [comment]
Il left a mess to Clickatell support and wait for an answer. BUT ...
I try to send é in unicode throught API and the result is ... that works! ;-)
...&unicode=1&text=00E9

I assume the answer: yes it's considered as unicode.

**Comment by rmarinier** [comment]
URLENCODe works fine too for accentued char.

**Comment by antonraharja** [comment]
tested via Nexmo, it shown as expected, not unicode

anton

**Comment by antonraharja** [comment]
also ok via Kannel, my cellphone is LG G2 (just in case its cellphone's issue too, not sure)

anton

**Comment by rmarinier** [comment]
OK. I assume that's a specificity to clickatell cause, as i show in previous post: when i send only 00E9 whith unicode=1 (...&unicode=1&text=00E9) i receive é on my phone (iphone). I've also tried on LG smartphone, same results.

Rod
