### ISSUE TITLE
Queue Rotation for multiple users

### ISSUE THREAD

**Issue by starnetwork** [antonraharja/playSMS#466]
Hi,
if multiple users sending messages, it's can take some time for the last users to get they messages
for example, for this order of sending: 
User 1: send 100000 Messages
User 2: send 50000 Messages
User 3: do 2factor authentication and send 1 message
User 3 that send one message will get this message only after user 1 and user 2 messages are sent

in my opinion, the best solution for that, is do rotation in the Queue,
mean, sending user 1 one message,  user 2 one message, user 3 one message, and than user 1 and user 2 messages in rotation.

Please advice,

**Comment by antonraharja** [comment]
Queues are processed in parallel, you can see the code for it in `/usr/local/bin/playsmsd` (starts from approx. line 244)

**Comment by antonraharja** [comment]
ref: #454 multiple submission to the gateway upon sendsms
