### ISSUE TITLE
configurable filename for outgoing sms

### ISSUE THREAD

**Issue by astrakid** [antonraharja/playSMS#473]
for better analysis i would like to have the filename configurable. in smstools-gateway it is hardcoded in fn.php as "out.$smsid. I would appreciate to have a timestamp in there. this is no issue, but a request for change.
Possible solution:
another prefix, with using php-functions. I edited fn.php in this way (just grepped the fn.php for "out", so line numbers are missing, but just as example):

        $outprefix=date('Ymd_His', time())."_playsms";
                $fn = $smstools_param['spool_dir']."/sent/$outprefix.$gpid.$uid.$smslog_id";
                $efn = $smstools_param['spool_dir']."/failed/$outprefix.$gpid.$uid.$smslog_id";
                $fn = $smstools_param['spool_dir']."/sent/$outprefix.0.$uid.$smslog_id";
                $efn = $smstools_param['spool_dir']."/failed/$outprefix.0.$uid.$smslog_id";
                                // if not a DLR then route it to incoming handler
        $outprefix=date('Ymd_His', time())."_playsms";
        // try to backup outgoing file first
        $fn_bak = $smstools_param['spool_bak']."/outgoing/$outprefix.$sms_id";
        if (is_dir($smstools_param['spool_bak'].'/outgoing')) {
        $fn = $smstools_param['spool_dir']."/outgoing/$outprefix.$sms_id";

**Comment by antonraharja** [comment]
there will be problem (or at least need to also work on it) to check dlr
