### ISSUE TITLE
Configurable path of playsmsd.conf

### ISSUE THREAD

**Issue by astrakid** [antonraharja/playSMS#476]
playSMS installation script is fully configurable regarding pathes of installation. It would be great to have the folder for configuration file (playsmsd.conf, by default placed in /etc) configurable as well.
e.g.
in install.conf use PLAYSMS_DAEMONCONF="/etc"
in installation script use $PATHDAEMONCONF instead of "/etc"

that makes it possible to have a complete customizable location of the complete installation (me for example uses to have every related file in /opt/<application>, that makes it easy for operational tasks to act.

**Comment by antonraharja** [comment]
ref, multi playsmsd instances (1 server can have multiple installation of playSMS):
https://github.com/antonraharja/playSMS/commit/c0effdb645d513cf3bd48d26a04375510f03dfee
