### ISSUE TITLE
latest github version incoming sms  with ' not processed. seems the ' is not being escaped.

### ISSUE THREAD

**Issue by guyt101z** [antonraharja/playSMS#477]
Incoming messages with ' in the message not being entered into the database but it is fwd ok via email. the ' seems to not be properly escaped in the incoming.  Sending ' is fine. Possibly other characters may be an issue.

**Comment by antonraharja** [comment]
what gateway do you use ?

**Comment by guyt101z** [comment]
Nexmo ..i also wrote up gateway for plivo.com i want to contribute it how
can i submit the code to you?

**Comment by watermelonjuice** [comment]
Hi,

I'm interested in your Plivo gateway. Do you mind sharing it?

**Comment by ClementN** [comment]
Hello,

Is the Plivo gateway, still available ?

Thank you,
