### ISSUE TITLE
the status shown that playSMS Daemon is not running although IT IS running

### ISSUE THREAD

**Issue by astrakid** [antonraharja/playSMS#479]
I have the latest version from master branch installed. the web-gui tells me that my playsms daemon is not running, although it IS running and sms are delivered to smsservertools coorectly and are processed fine. My sent SMS shows the right status (first yellow, after successful sending it turns to green).
i have playsms daemon running in custom folders (/opt/playsms/bin/* and config file there as well).

**Comment by antonraharja** [comment]
make sure that you're using playsmsd from the package (from the source folder, on daemon folder), and then when you run `playsmsd check_json` it should shown some output in json format

**Comment by astrakid** [comment]
this is the output:

[xxxxxxxxxx:gxxxa] /opt/playsms/bin> playsmsd check_json
{"PLAYSMSD_CONF":".\/playsmsd.conf","PLAYSMS_PATH":"\/opt\/playsms\/www","PLAYSMS_LIB":"\/opt\/playsms\/www\/lib","PLAYSMS_BIN":"\/opt\/playsms\/bin","PLAYSMS_LOG":"\/opt\/playsms\/log","DAEMON_SLEEP":1,"ERROR_REPORTING":"1","IS_RUNNING":true,"PIDS":{"schedule":"5381","dlrssmsd":"5383","recvsmsd":"5385","sendsmsd":"5387"}}[xxxxxxxxx:gxxxa] /opt/playsms/bin>

looks fine, right?

**Comment by astrakid** [comment]
any idea?

**Comment by yahia007** [comment]
I have this issue too.

The changes doesn't fix it!

Could it be because of permission issue?
