### ISSUE TITLE
Behaviour in email to sms

### ISSUE THREAD

**Issue by tapule** [antonraharja/playSMS#485]
I'm testing the module email to sms in PlaySms 1.1. This is the configuration that I'm using:
![captura](https://cloud.githubusercontent.com/assets/3315610/9461775/2b748a7e-4b11-11e5-831d-9d1deb4a35d3.png)

And this is the email format:

Email from: depends on the setting the address might be validated against sender's email
Email subject: [username] [PIN] [message]
Email body: [number], [number], [@User], [#Group]

I get two problems:
1.- In the final sms, the text sent is "[username] [PIN] [message]" and I don't understand why it includes the username and pin from the sender.
2.- Seems that when PlaySms reads the email, it does not mark it as readed in the mailbox, so later it reads the same mail again and sent again the same sms. This happens forever until you delete the email manually from the mailbox.

Can you help me??

**Comment by antonraharja** [comment]
please ask help/support question in user forum
