### ISSUE TITLE
Missing First Word in Message

### ISSUE THREAD

**Issue by astravoice** [antonraharja/playSMS#490]
Hello.

I was testing this and noticed that if you simulate a test message, the first word is missing.

Steps.

https://localhost/index.php?app=main&inc=gateway_dev&route=simulate&op=simulate

Enter Message

"This is a test message."

Step 2.

Go to Inbox
https://localhost/index.php?app=main&inc=feature_report&route=user_inbox&op=user_inbox

"is a test message."

**Comment by ippbx** [comment]
Yes I noticed same problem.

**Comment by antonraharja** [comment]
I tested this and the message went to Sandbox as it suppose to, not Inbox, and I got full message on Sandbox. Can you screenshot how you test it and where do you see your message ?

**Comment by astravoice** [comment]
Thanks. I am not sure I understand the response.
Where is "Sandbox"

I am using v1.3

Where is Sandbox menu?

**Comment by astravoice** [comment]
![screen shot 2015-09-18 at 11 31 09 am](https://cloud.githubusercontent.com/assets/3717647/9963339/d2913740-5df8-11e5-8943-afa39bf0dd84.png)

**Comment by ippbx** [comment]
I have it routing to inbox and then it loses first word.

**Comment by antonraharja** [comment]
unless you guys give me details on how you actually send the test message, what were configured in Route incoming, and other changes you made, I cannot help. I tested on 2 servers and I couldn't replicate this issue. I tried to route Sandbox to Inbox too. I'm using 1.3.

**Comment by astravoice** [comment]
![screen shot 2015-09-18 at 12 52 51 pm](https://cloud.githubusercontent.com/assets/3717647/9965433/381aabae-5e04-11e5-81ee-7f12e9214786.png)

**Comment by astravoice** [comment]
![screen shot 2015-09-18 at 12 55 48 pm](https://cloud.githubusercontent.com/assets/3717647/9965503/a235fc3c-5e04-11e5-8e31-1d067a10f908.png)

**Comment by astravoice** [comment]
![screen shot 2015-09-18 at 12 56 30 pm](https://cloud.githubusercontent.com/assets/3717647/9965519/b78a3648-5e04-11e5-94ae-a97506f53355.png)

**Comment by astravoice** [comment]
![screen shot 2015-09-18 at 12 57 03 pm](https://cloud.githubusercontent.com/assets/3717647/9965544/dd4fafc0-5e04-11e5-9f64-f96a77e3d760.png)

**Comment by astravoice** [comment]
I have this in the Database.

select * from playsms_tblRecvSMS;

|           0 | 33 |              2 | 2015-09-12 16:44:32 | 629876543210 | This is a message                            | 17082920638  | dev      |
|           0 | 34 |              2 | 2015-09-13 04:44:39 | 629876543210 | This is a message                            | 17082920638  | dev      |


select * from playsms_tblSMSIncoming;

|           0 |    33 |            0 |      1 |            | dev        | 629876543210 | 17082920638  |            | This is a message                            | 2015-09-12 16:44:32 |         1 |
|           0 |    34 |            0 |      1 |            | dev        | 629876543210 | 17082920638  |            | This is a message                            | 2015-09-13 04:44:39 |         1 |


select * from playsms_tblSMSInbox;

|  1442116491 |    23 |            1 | 629876543210 | 17082920638  |      1 | is a message                                                                      | 2015-09-12 09:40:40 |              |
|  1442116491 |    24 |            1 | 629876543210 | 17082920638  |      1 | is a message                                                                      | 2015-09

**Comment by astravoice** [comment]
I have a customized inbound routing script that calls.

Incoming.php

<?php
//I get all the vars normally for brevity I do this.

$message = $_REQUEST['message'];
recvsms($sms_datetime, $sms_sender, $message, $sms_receiver, 'dev');

//I see the message is correct in the Database but somewhere between this script and the script that is responsible for putting it into the Inbox table in the DB its removing some text.
?>

**Comment by antonraharja** [comment]
ok, now lets examine the log file:

please set your loglevel to 3 from config.php, and then restart playsmsd. next to tail the log file and try 1 test to simulate incoming SMS:

```
tail -f /var/log/playsms/playsms -n0 | tee debug1.txt
```

once that single test is done you can ctrl+c and read `debug1.txt`, sanitize private information and paste here, or paste in pastebin and paste the link here

anton

**Comment by astravoice** [comment]
sms.example.us 2015-09-19 21:45:19 PID55fe0fafad562 - L3 recvsms # isrecvsmsd:1 dt:1442713550 sender:+19174170964 m:Three word test receiver:17082920638 smsc:dev
- - 2015-09-19 21:45:20 PID55f5adaee7689 - L3 recvsmsd # id:50 dt:1969-12-31 19:00:00 sender:+19174170964 m:Three word test receiver:17082920638 smsc:dev
- - 2015-09-19 21:45:20 PID55f5adaee7689 - L3 inboxgroup # forwardcatchall id:3 s:+19174170964 r:17082920638 m:word test
- - 2015-09-19 21:45:20 PID55f5adaee7689 - L2 recvsms_inbox_add # saving sender:+19174170964 receiver:17082920638 target:admin reference_id: message:word test
- - 2015-09-19 21:45:20 PID55f5adaee7689 - L2 recvsms_inbox_add # saving sender:+19174170964 receiver:17082920638 target:admin reference_id:
- - 2015-09-19 21:45:20 PID55f5adaee7689 - L2 recvsms_inbox_add # saved id:40 sender:+19174170964 receiver:17082920638 target:admin
- - 2015-09-19 21:45:20 PID55f5adaee7689 - L3 recvsms_inbox_add # send email from:sms@example.us to:max@example-email.com message:[word test]
- - 2015-09-19 21:45:20 PID55f5adaee7689 - L2 sendmail # start from:sms@example.us to:max@example-email.com subject:Message from max (+18005551212)
- - 2015-09-19 21:45:21 PID55f5adaee7689 - L2 sendmail # end from:sms@example.us to:max@example-email.com subject:Message from max (+18005551212)
- - 2015-09-19 21:45:21 PID55f5adaee7689 - L3 recvsms_inbox_add # sent email from:sms@example.us to:max@example-email.com
- - 2015-09-19 21:45:21 PID55f5adaee7689 - L3 recvsms_process # dt:1969-12-31 19:00:00 sender:+18005551212 m:Three word test receiver:17082920638 smsc:dev
- - 2015-09-19 21:45:21 PID55f5adaee7689 - L3 recvsms_process # intercepted datetime:1969-12-31 19:00:00 sender:+18005551212 receiver:17082920638 message:Three word test
~

**Comment by antonraharja** [comment]
I see, do you use Inbox group ? can you remove your config/setup on Inbox group and then test again

**Comment by ippbx** [comment]
I disabled in GUI the group inbox and then first word came through.

**Comment by antonraharja** [comment]
ok, please edit your `plugin/feature/inboxgroup/fn.php` and go to line 64.

change this line:

```
inboxgroup_forwardcatchall($data, $log_in_id, $sms_sender, $msg['content']);
```

into this line:

```
inboxgroup_forwardcatchall($data, $log_in_id, $sms_sender, $message);
```

save it, and then restart playsmsd, and then re-enable your inbox group and test

ref:
https://github.com/antonraharja/playSMS/blob/master/web/plugin/feature/inboxgroup/fn.php#L64

**Comment by ippbx** [comment]
Yes all words came through, thanks a million.

**Comment by antonraharja** [comment]
but this isn't a bug, it was designed to remove the keyword. message processed by Inbox Group was just like any other message that came to any other feature, their format is: KEYWORD <space> CONTENT

**Comment by astravoice** [comment]
Maybe a quick if statement would be worthwhile in the case a KEYWORD is not found then you dont run into the problem.

**Comment by astravoice** [comment]
I appreciate the fix. None the less.

**Comment by antonraharja** [comment]
Ah yes, it was caught by catchall account. may be catchall will receive forward in full message rather then missing the keyword
