### ISSUE TITLE
playsms-1.3.1 with sms receive with ' character (apostrophe)

### ISSUE THREAD

**Issue by manuskysurfeur** [antonraharja/playSMS#494]
Hello all,

I'm a new user of "Playsms" and I'm very surprised with your application. It's very easy to use and we can do a lot of things. Very good job ^^

I use PlaySms version 1.3.1 with gammu. All is working, I'm able to send and receive sms.

I just notice an issue with playsms, I never receive sms with ' character (apostrophe character) on my playsms inbox...

Please, could you help me in order to resolve this issue ?

I thank you in advance.

**Comment by antonraharja** [comment]
Hi,

Edit this file:
https://github.com/antonraharja/playSMS/blob/master/web/plugin/gateway/gammu/fn.php#L161

Go to line 161 and 189, add `addslashes()` to `$parts_message`.

Change from this:
```
recvsms($parts_datetime, $parts_sender, $parts_message, $sms_receiver, $smsc);
```

To this:
```
recvsms($parts_datetime, $parts_sender, addslashes($parts_message), $sms_receiver, $smsc);
```

**Comment by manuskysurfeur** [comment]
Hello Anton,

I modified both line 161 and 189 like you said but I still have the
problem...


Could you help me ?

I thank you.


Cordialement,
*Emmanuel USCLADE | Administrateur Systèmes et Réseaux*

45 rue Clos Four - 63056 CLERMONT-FERRAND Cedex 2

Tél. +33 (0)4 73 17 65 19

emmanuel.uscladecentrefrance.com <emmanuel.usclade@centrefrance.com>

<http://www.lamontagne.fr>


La feuille est sans doute mieux dans l’arbre que dans la corbeille.

2015-11-02 3:09 GMT+01:00 Anton Raharja <notifications@github.com>:

**Comment by manuskysurfeur** [comment]
Hello Anto,

I made a mistake, your workaround is working fine.

I thank you


Cordialement,
*Emmanuel USCLADE | Administrateur Systèmes et Réseaux*

45 rue Clos Four - 63056 CLERMONT-FERRAND Cedex 2

Tél. +33 (0)4 73 17 65 19

emmanuel.uscladecentrefrance.com <emmanuel.usclade@centrefrance.com>

<http://www.lamontagne.fr>


La feuille est sans doute mieux dans l’arbre que dans la corbeille.

2015-11-02 9:26 GMT+01:00 Emmanuel Usclade <
emmanuel.usclade@centrefrance.com>:

**Comment by ShadowDestroyer** [comment]
Hello to you two,

I have done this modification. 
Playsms catch the sms and sen to the sender the correct sms answer.
But I can not see the message in the page where answer are sum up. So I can not see every people who have answer to my quiz.
@manuskysurfeur do you got the same problem?
Do you have any solution or advice ?

Thank's a lot for your help.

Furthermore if you are interested, I added a column "name" to the page which make appear the name of the sender if we can find his name in the phonebook. I can send you the code.

**Comment by manuskysurfeur** [comment]
Hi ShadowDestroyer,

I've never had this kind of problem...

Regards.
