### ISSUE TITLE
Multiple iteration check

### ISSUE THREAD

**Issue by sbrawner** [antonraharja/playSMS#496]
Have found that when stopping and restarting playsms in ubuntu that sometimes processes are not terminated.  If playsms is started using /usr/local/bin playsms start, there is no check on whether processes are already running and this can lead to multiple instances of texts being sent, etc.

Perhaps a proper service creation?

**Comment by antonraharja** [comment]
what version are you using ?

anton

**Comment by sbrawner** [comment]
latest 1.3.1.

**Comment by antonraharja** [comment]
Ok. Check playsmsd.php in daemon folder in source folder. There is a check
of running daemon.

Anton
