### ISSUE TITLE
race condition on saving user's credit during sendsmsd

### ISSUE THREAD

**Issue by antonraharja** [antonraharja/playSMS#502]
ref:
https://forum.playsms.org/t/billing-issue-in-playsms/461/8

**Comment by antonraharja** [comment]
rate_deduct() called after successful delivery to gateway on sendsms_process(). rate_deduct() calls rate_setusercredit() which is updating tblUser's credit with balance value.

problem occurred when the balance, uid and mktime() value set in rate_setusercredit() is the same due to parallel process by playsmsd. current playsmsd will call sendsms_process() in parallel to speed up delivery.

what to do to fix this, I think I should refactor rate_setusercredit() so that it won't update with the same value, and also make sure that balance value is correct by checking current credit before deduct.

**Comment by antonraharja** [comment]
I found the solution, that is to completely change the way credit get and set, in `rate_setusercredit()` and `rate_getusercredit()`. both functions are hooked by plugin `credit`: `credit_hook_rate_setusercredit()` and `credit_hook_rate_getusercredit()`

**Comment by marwanzak** [comment]
Hello @antonraharja 
We are facing the same problem when we send about 1000 messages a time. Did you fix the problem?

**Comment by antonraharja** [comment]
I think this is dup #515 so I'll close this one too
