### ISSUE TITLE
Access blocked when redirect from paypal

### ISSUE THREAD

**Issue by hieunt142** [antonraharja/playSMS#505]
I want to integrate Paypal into my system for allowing user buy credits.
I've already read all instructions from Paypal to implement this. For my system, use PDT was OK
. But I want to use IPN method for more secure in my system. Unfortunately, there was a weird problem.
 - When user's payment has been made, they was redirected to  index.php?app=main&inc=core_auth&route=block instead of index.php?app=main&inc=core_auth&route=buy_success , then no background process was executed. If I set rm='2' (means return by POST method) this problem happened, in case rm=1 (means return by GET method), block page didn't appear, but page: index.php?app=main&inc=core_auth&route=buy_success was never called.
 - When I entered link: index.php?app=main&inc=core_auth&route=buy_success direct to browser, it was executed OK .
Did you ever meet this problem in the past ?
Or could you help me ? I'm stucking for some days .
Thanks you.

**Comment by antonraharja** [comment]
please use playSMS forum
