### ISSUE TITLE
recover password

### ISSUE THREAD

**Issue by ressel87** [antonraharja/playSMS#506]
When I access index.php?app=main&inc=core_auth&route=forgot
I get Internal server error 500.

2016/01/08 19:28:37 [error] 2518#0: *228 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Class 'Gregwar\Captcha\CaptchaBuilder' not found in /var/www/myweb/web/plugin/core/auth/forgot.php on line 103" while reading response header from upstream, client: 18x.10x.xx.xx, server: mydomain.tld, request: "GET /index.php?app=main&inc=core_auth&route=forgot HTTP/1.0", upstream: "fastcgi://unix:/var/lib/php5-fpm/web1.sock:", host: "mydomain.tlf", referrer: "http://mydomain.tld/index.php?app=main&inc=core_auth&route=login"

Debian Jeesie, Nginx 1.8, PHP 5.6.14-0+deb8u1

**Comment by antonraharja** [comment]
your installation was not complete, please post in user forum
