### ISSUE TITLE
playsms webservices

### ISSUE THREAD

**Issue by andreas20** [antonraharja/playSMS#513]
When i use web services to schedule an sms send, the smsc parameter is not used as expected, and not inserted in the MySQL table also, table: _playsms_tblSMSOutgoing_queue_ .column: smsc
I am using the below but the smsc is not used
http://192.168.1.xxxx/playsms/index.php?app=ws&op=pv&nofooter=1&format=xml&h=7ebbfd472a1b01e4a44aa00f3e5d18bb&unicode=1&u=admin123&p=admin123&to=35799888888&from=NICSMSPARK&msg=%hello&schedule=2016-02-10+05:34&smsc=smpp2 

Whys that? Any alternative?

**Comment by sbrawner** [comment]
In the code in fn_webservices.php is says this:
```
function webservices_pv($c_username, $to, $msg, $type = 'text', $unicode = 0, $nofooter = FALSE, $footer = '', $from = '', $schedule = '') {
	$ret = '';
	if ($c_username && $to && $msg) {
		
		// send SMS, note that we can't let user to define SMSC for now
```

**Comment by antonraharja** [comment]
yes, smsc can't be set by user, it needs to be configured in outgoing route
