### ISSUE TITLE
Credits Issue in PlaySMS v1.4

### ISSUE THREAD

**Issue by starnetwork** [antonraharja/playSMS#515]
Hi,
after upgrade to v1.4 from 1.0 RC8 and update the db in the next steps
db/playsms-upgrade_1.0-rc8_to_1.0.sql
db/playsms-upgrade_1.0_to_1.3.1.sql
db/playsms-upgrade_1.3_or_1.3.1_to_1.4.sql
any user that I add credits to him, the User credits are reset to 0
it's same from both GUI and API

mean, If even the admin user have 120 credits, and I add 50 credits to the admin
the admin credits updated to 0

Please check it
Regards,

**Comment by astrakid** [comment]
i suppose only to use db/playsms-upgrade_1.0_to_1.3.1.sql which is still the master version...
do the problems occur with "only" 1.3.1 as well?

regards,
andre

**Comment by starnetwork** [comment]
Hi andre,
1. my first version was RC8, not final
2. it's look like Anton familiar with that issue in v1.4
I have another installation with v1.3 and it's working well

**Comment by guyt101z** [comment]
This issue is in the add/update code. I don't have the time right now to trace it but I set a value in the database and deductions are working fine, listings etc. It is only the add/update have the problem. Hope this helps.

**Comment by starnetwork** [comment]
Hi,
I know, already did it, but we have automation via API to add / manage credits and it's not working :(

**Comment by antonraharja** [comment]
please follow discussion here: https://forum.playsms.org/t/inviting-interested-testers-on-billing-issue/880

thx

**Comment by starnetwork** [comment]
Hi Anton,
I did and from first view, it's look like it's work, thanks!
I will continue to check and keep you updated for any issue...

Thanks!

**Comment by antonraharja** [comment]
alright, if theres new issue please post as new bug. thanks.
