### ISSUE TITLE
2-Way sms infobip

### ISSUE THREAD

**Issue by skynett81** [antonraharja/playSMS#529]
hi . is there a way to set up a 2-way sms service  for plugin infobip ?

if not i want a way to set up a 2-way sms service with playsms .

**Comment by Althrin** [comment]
Are you trying to setup incoming and outgoing SMS with playsms? If so, this is already a feature, you will need to route the infobip incoming SMS to your callback.php so that PlaySMS can handle the receiving part. The sending part should be configured via Gateway and SMSC.
