### ISSUE TITLE
error

### ISSUE THREAD

**Issue by freedarwuin** [antonraharja/playSMS#530]
root@debian:~# gammu-smsd -c /etc/gammu-smsdrc
gammu-smsd[13826]: Error code: 1146, Error: Table 'playsms.outbox' doesn't exist
gammu-smsd[13826]: Table outbox not found, disconnecting!
gammu-smsd[13826]: Initialisation failed, stopping Gammu smsd: Error desconocido. (UNKNOWN[27])
Failed to run SMSD: Error desconocido.

**Comment by antonraharja** [comment]
not playSMS related issue
