### ISSUE TITLE
Not sending low credit notification to users

### ISSUE THREAD

**Issue by aizukanne** [antonraharja/playSMS#533]
I notice my playsms installation doesn't send low credit alerts to users when their units go below the set threshold. PlaySMS however sends an alert to the admin account when a user's threshold is below limit.

I my previous installations, users received alerts when their units went below threshold. Has this functionality been removed?

**Comment by antonraharja** [comment]
Its still there, I can't test this but it looks like no issue, I'm gonna need more feedback on this

**Comment by enumanc** [comment]
Hello, I have notice the same issue (in 1.4.2), it seems that in the file plugin/feature/credit/fn.php in the funtion _credit_low_notif that there is an issue located with this test:
if ($balance && $credit_lowest_limit && ($balance <= $credit_lowest_limit) && !$notified) {
...
}

The condition is never fulfilled, I changed with that condition and it is now better:
if ( ($balance <= $credit_lowest_limit) && $notified === true ) {
...
}

**Comment by antonraharja** [comment]
I suppose $balance can be zero, so I think you're right. I'll made this changes, thanks.
