### ISSUE TITLE
Adding POST support for PlaySMS webservice

### ISSUE THREAD

**Issue by bgth** [antonraharja/playSMS#548]
Hi Team,

Is it possible to add POST support for PlaySMS webservice? I can only see GET based SMS sending at present. Thanks alot.

**Comment by lowinger42** [comment]
I've successfully sent SMS using POST, have you tried it?

I looked into the source code, and the WebService API uses $_REQUEST[] everywhere, so it handles both GET and POST variables (you can even mix them).
