### ISSUE TITLE
Issue with Manage Gateway and SMSC

### ISSUE THREAD

**Issue by poojansharma** [antonraharja/playSMS#549]
I recently installed playSMS and kannel. I could successfully configure kannel and i tested sms push and its working perfectly fine from kannel.
But now i have to configure pull message with keyword, but when i try to add gateway in playsms i'm unable to do it because when i click on Settings -> Manage Gateway and SMSC it doesnot display anything, a blank page appears. Help me please

**Comment by seanwhe** [comment]
Linux kannel2 4.4.0-127-generic #153-Ubuntu SMP Sat May 19 10:58:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

PHP 7.0.30-0ubuntu0.16.04.1 (cli) ( NTS )


I had the same problem

Can login to playsms but when I select 
http://192.168.22.92/playsms/index.php?app=main&inc=core_gateway&op=gateway_list

I am presented with 

This page isn’t working
192.168.22.92 is currently unable to handle this request.
HTTP ERROR 500

Looking in the apache2 error log I have

Thu May 24 18:55:54.309939 2018] [:error] [pid 18459] [client 192.168.1.40:56498] PHP Fatal error:  Uncaught Error: Call to undefined function simplexml_load_string() in /var/www/html/playsms/lib/fn_core.php:823\nStack trace:\n#0 /var/www/html/playsms/plugin/core/gateway/fn.php(197): core_xml_to_array('<?xml version="...')\n#1 /var/www/html/playsms/plugin/core/gateway/gateway.php(210): _gateway_display()\n#2 /var/www/html/playsms/inc/app/main.php(33): include_once('/var/www/html/p...')\n#3 /var/www/html/playsms/index.php(34): include('/var/www/html/p...')\n#4 {main}\n  thrown in /var/www/html/playsms/lib/fn_core.php on line 823, referer: http://192.168.22.92/playsms/index.php?app=main&inc=core_main_config&op=main_config

apt install php7.0-xml

systemctl restart apache2

All fixed. Hope this helps

**Comment by azaman2204** [comment]
I am having problem when trying to display Report All Users andAll Sent Messages in Report. Other reports are OK
No errors reported in apache error log.
using php7.4.3 and mariadb
