### ISSUE TITLE
Unable to add groups in playsms 1.4

### ISSUE THREAD

**Issue by poojansharma** [antonraharja/playSMS#551]
I was recently facing the issue of adding groups in playSMS v1.4. Then upon carefully examining the code i found out a issue in the code inside /playsms/plugin/feature/phonebook/fn.php.
In the function **phonebook_group_add** at line no. 433, was the below code:
```
if ($db_row = dba_fetch_array($db_result)) {
	$flag_sender = 0;
}
```
Here if a row is returned flag_sender is set to 0 but else flag_sender is empty which was not accepted by the query so i modified the code as below:
```
if ($db_row = dba_fetch_array($db_result)) {
	$flag_sender = 0;
} else {
	$flag_sender = 1;
}
```
Then it worked for me. Hope i'm doing it right.

**Comment by Althrin** [comment]
You have saved me, thank you so much for this. The subscribe feature is not working either and I really just needed grouping to work in the meantime. Thank you so much!

**Comment by manio** [comment]
Hi guys!
I am facing the same problem - and discovered the same results when debugging. I am running it on php7. The query is evaluating to:
`INSERT INTO playsms_featurePhonebook_group (uid,name,code,flag_sender) VALUES ('1','Test','TEST','')`
This leads to:
`ERROR 1366 (HY000): Incorrect integer value: '' for column 'flag_sender' at row 1`

@antonraharja
I believe the same issue is reported here:
https://forum.playsms.org/t/unable-to-add-group-8/1062
https://forum.playsms.org/t/cannot-add-groups/1258
I can prepare a PR for this is you wish, let me know :)
