### ISSUE TITLE
Step By Step Guide to Install Kannel SMPP with PlaySMS

### ISSUE THREAD

**Issue by helpingnhandy** [antonraharja/playSMS#552]
Dear Techies,

I am new to Kannel SMPP and would like to know how to install Kannel SMPP with PlaySMS.

I have Vodafone IP Address and Login Credential to send Bulk SMS. Also got CentOS 6.5 VPS for this.

Kindly share step by step guide to install Kannel SMPP with Configuration Information.

Looking forward to your kind reply.

Many Thanks

**Comment by antonraharja** [comment]
please discuss on forum, thx
