### ISSUE TITLE
Apache server + nexmo + playSMS    SMS in que not sending.

### ISSUE THREAD

**Issue by slagteriet** [antonraharja/playSMS#553]
Hi, Anton.

I've setup your great playSMS on my online apache server(not localhost), i put the db on my server phpMyAdmin. 
I put in Nexmo secret / voucher, the sms only get to que, and I don't receive any sms..

Do you know what could be the reason why it won't send ?

![sk__rmbillede_2017-02-06_kl _13 36 46](https://cloud.githubusercontent.com/assets/23503773/22647422/a248b1a4-ec71-11e6-9397-6fc0749e39ea.png)

**Comment by Althrin** [comment]
Under the gateways and SMSC settings, have you added an SMSC for Nexmo? I know you can click the folder for the gateway and edit settings, but those settings seem to not do anything. Can you attach a screenshot of the way you have nexmo configured?

**Comment by antonraharja** [comment]
please continue discussion on forum, thx
