### ISSUE TITLE
BUG: PlaySMS Add Credit Feature Issue with SQL Query

### ISSUE THREAD

**Issue by ghost** [antonraharja/playSMS#555]
Hello Guys,

Sorry for my English, I speak French
I think that there is something wrong in PlaySMS.
On a fresh install, I can't add credit to an account. I've noticed that There is an error in SQL Statement who add lines in playsms_featureCredit table

My configuration
PlaySMS 1.4 using Kannel
OS : Ubuntu 16.04 x64
PHP Version : 7.0
MySQL 5.7

Here is the log

> 127.0.0.1 localhost 2017-03-13 16:28:15 PID58c6ba8fcfb8d admin L4 dba__query # q:SELECT name FROM playsms_tblACL  WHERE  id='0' AND flag_deleted='0' 
127.0.0.1 localhost 2017-03-13 16:28:15 PID58c6ba8fcfb8d admin L4 dba__query # q:SELECT url FROM playsms_tblACL  WHERE  id='0' AND flag_deleted='0' 
127.0.0.1 localhost 2017-03-13 16:28:15 PID58c6ba8fcfb8d admin L4 dba__query # q:SELECT username FROM playsms_tblUser WHERE flag_deleted='0' AND uid='1'
127.0.0.1 localhost 2017-03-13 16:28:15 PID58c6ba8fcfb8d admin L4 dba__query # **q:SELECT parent_uid FROM playsms_tblUser  WHERE  flag_deleted='0' AND uid='1' AND status='4'** 
127.0.0.1 localhost 2017-03-13 16:28:15 PID58c6ba8fcfb8d admin L4 dba__query # q:SELECT username FROM playsms_tblUser WHERE flag_deleted='0' AND uid='1'
127.0.0.1 localhost 2017-03-13 16:28:15 PID58c6ba8fcfb8d admin L4 dba__query # q:SELECT status FROM playsms_tblUser WHERE flag_deleted='0' AND uid='1'
127.0.0.1 localhost 2017-03-13 16:28:15 PID58c6ba8fcfb8d admin L4 dba__query # **q:INSERT INTO playsms_featureCredit (parent_uid,uid,username,status,create_datetime,amount,flag_deleted) VALUES ('','1','admin','2','2017-03-13 09:28:15','500','0')**
127.0.0.1 localhost 2017-03-13 16:28:15 PID58c6ba8fcfb8d admin L4 dba__query # q:SELECT @@IDENTITY
127.0.0.1 localhost 2017-03-13 16:28:15 PID58c6ba8fcfb8d admin L3 credit_add # **fail to save parent_uid: uid:1 username:admin amount:500**
2017-03-13 16:28:15 PID58c67345bd890 - L4 dba__query # q:SET NAMES utf8
2017-03-13 16:28:15 PID58c67345bd890 - L4 dba__query # q:SELECT registry_key, registry_value FROM playsms_tblRegistry  WHERE  uid='1' AND registry_group='core' AND registry_family='main_config' 

In the log, You'will see a SQL Query which is asking for a parent_uid from users table with status = 4. I don't think where is a status code 4 and it results on an empty parent_uid result
The INSERT INTO statement gives an error because parent_uid value is **EMPTY**, which result on an error when trying to add credit for a user.

Do someone know how to fix it ?

**Comment by Althrin** [comment]
There are many users who cannot add credit at the moment, I think the best we can do is wait for the developer to come back to help us all.

**Comment by bosskhalif** [comment]
I've managed to fix it temporary. I've modified the playsms_featureCredit table (with PhpMyAdmin) and modify the parent_uid colum to accept empty string or using 0 as default value. Since then, no more error appears
Adding credit is working like a charm !

**Comment by Althrin** [comment]
Oh very nice! Good information. Now if only my Subscribe Replies were working, the one feature I wanted this software for.

**Comment by Althrin** [comment]
Might also want to change the title of this so it is easily found for people with the same issue. Maybe something like "BUG: PlaySMS Add Credit Feature Issue with SQL Query"

**Comment by bosskhalif** [comment]
Thank you for the title ! I was afraid that people won't really understand my english. The title is changed. For your problem (Subscribe Replies), i'am afraid that I can't help. I'm using PlaySMS just for sending SMS... Nothing else... Hope you'ill find a solution

**Comment by antonraharja** [comment]
when credit_add() to user (w/o parent_uid, only subusers has it) then user_getparentbyuid() should return 0 instead of FALSE
