### ISSUE TITLE
Webservice no credit (code 103) broken

### ISSUE THREAD

**Issue by cdarken** [antonraharja/playSMS#557]
What happened with the response when there's no credit for the user? You added the comment `this doesn't work, but not much an issue now`. What does that mean?

**Comment by antonraharja** [comment]
theres no `$ok[$i] == 2', $ok returns TRUE or FALSE only. in sendsms() playSMS calculate whether or not sender have enough credit, it will fail if user has no credit.

**Comment by cdarken** [comment]
@antonraharja but shouldn't send some kind of response for the api user to understand what's happening?

**Comment by antonraharja** [comment]
Yes, but thats feature request not current issue. Please test and let me know how yoy want it in new support ticket, this ticket has been closed.
