### ISSUE TITLE
issue with PlaySms configuration 

### ISSUE THREAD

**Issue by asifahamedsi1** [antonraharja/playSMS#561]
i have successfully configured playsms in centos 7 using below instruction
https://github.com/antonraharja/playSMS/blob/master/INSTALL.md

when try accessing playsms http://IP/playsms/ i am getting following and i suppose to get a playsms login page, please help

  | Name | Last modified | Size | Description
-- | -- | -- | -- | --

  | Parent Directory |   | - |  
  | config-dist.php | 2017-09-16 17:37 | 2.8K |  
  | config.php | 2017-09-16 17:58 | 2.8K |  
  | inc/ | 2017-09-16 17:37 | - |  
  | index.php | 2017-09-16 17:37 | 3.1K |  
  | init.php | 2017-09-16 17:37 | 13K |  
![screenshot from 2017-09-16 18-14-34](https://user-images.githubusercontent.com/30936963/30512927-fb699d14-9b0a-11e7-94d8-0a0e6275320d.png)

  | lib/ | 2017-09-16 17:37 | - |  
  | plugin/ | 2017-09-16 17:37 | - |  
  | storage/ | 2017-09-16 17:37 | - |

**Comment by astrakid** [comment]
Looks like you havn't php Files enabled in Webserver Konfiguration.
Index.php should be called but isn't.

Von meinem c64mobile gesendet

**Comment by asifahamedsi1** [comment]
Thank you for your quick response, since I am new can you please guide me
how to enable php files.


On 16-Sep-2017 6:23 PM, "Andre G" <notifications@github.com> wrote:

Looks like you havn't php Files enabled in Webserver Konfiguration.
Index.php should be called but isn't.

Von meinem c64mobile gesendet

> Am 16.09.2017 um 16:15 schrieb asifahamedsi1 <notifications@github.com>:
>
> i have successfully configured playsms in centos 7 using below instruction
> https://github.com/antonraharja/playSMS/blob/master/INSTALL.md
>
> when try accessing playsms http://IP/playsms/ i am getting following and
i suppose to get a playsms login page, please help
>
> Name Last modified Size Description
> | Parent Directory | | - |
> | config-dist.php | 2017-09-16 17:37 | 2.8K |
> | config.php | 2017-09-16 17:58 | 2.8K |
> | inc/ | 2017-09-16 17:37 | - |
> | index.php | 2017-09-16 17:37 | 3.1K |
> | init.php | 2017-09-16 17:37 | 13K |
>
>
> | lib/ | 2017-09-16 17:37 | - |
> | plugin/ | 2017-09-16 17:37 | - |
> | storage/ | 2017-09-16 17:37 | - |
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/antonraharja/playSMS/issues/561#issuecomment-329971450>,
or mute the thread

**Comment by astrakid** [comment]
https://en.m.wikipedia.org/wiki/Webserver_directory_index

Von meinem c64mobile gesendet

> Am 16.09.2017 um 16:48 schrieb asifahamedsi1 <notifications@github.com>:
> 
> Thank you for your quick response, since I am new can you please guide me
> how to enable php files.
> 
>

**Comment by asifahamedsi1** [comment]
@astrakid you were correct after enabling PHP it is working fine, Thank you for your prompt support..... much appreciated.
