### ISSUE TITLE
Unable to receive message sent from playsms but i am able to send messages from command (gammu)

### ISSUE THREAD

**Issue by asifahamedsi1** [antonraharja/playSMS#562]
I have configured playsms and gammu in centos7 
after sending message from playsms i got the notification that "Your message has been delivered to queue (queued:1 failed:0)" but for some reason it is not receiving.

i have also tried to send sms through command : gammu sendsms TEXT mobilenumber -text and i can receive the message, that means gammu is working fine and there is some issue with playsms communicating with gammu, please help 

attached is the playsms log
[playsms.txt](https://github.com/antonraharja/playSMS/files/1309042/playsms.txt)

**Comment by asifahamedsi1** [comment]
Can someone help on this please ??

**Comment by edilsons** [comment]
Everything seems to be ok with playsms-gammu communication. As your log says:

 PID59be4d205244f - L2 gammu_hook_sendsms # saving outfile:[/var/spool/gammu/outbox/OUTA20170917_102328_00_+971551093997_11100011100010.txtd] smsc:gammu
- - 2017-09-17 10:23:28 PID59be4d205244f - L2 gammu_hook_sendsms # saved outfile:[/var/spool/gammu/outbox/OUTA20170917_102328_00_+971551093997_11100011100010.txtd] smsc:gammu

Maybe gammu is having trouble reading out files. Take a look

**Comment by asifahamedsi1** [comment]
yes the actual problem was with gammu-smsd and for some reason it was not working, i have reconfigured gammu and it is working fine,i am able to send sms using playsms.

now i need help to configure to receive messages in playsms inbox
