### ISSUE TITLE
Play SMS

### ISSUE THREAD

**Issue by PlaySMSIssue** [antonraharja/playSMS#567]
Hi,

I am using Playsms for sending the email from one of my application kennel as a gateway.

1) I am using the below URL example for sending email

http://localhost:13131/cgi-bin/sensms?username=username&password=password&to=7896541236&text=welcome+message

Could you please let me know what json or xml response I will get on sending the above rest url.

2) I am trying to send the sms from playsms gui but always it tells your shows your message has been delivered to queue. At the same time sms is not delivered to the destination number and I am not able to view it in the sent messages also it is always empty.

Request you to help me to resolve this

**Comment by antonraharja** [comment]
kannel plugin gateway is already available on playSMS, please discuss in forum, thx
