### ISSUE TITLE
Web page is blank

### ISSUE THREAD

**Issue by MAPIIIAJI** [antonraharja/playSMS#570]
I use this (https://github.com/antonraharja/playSMS/blob/master/INSTALL.md) instruction for installation, but receive this error: 
[php7:error] [pid 1054:tid 140285266831104] [client 213.230.92.13:15605] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function themes_submenu(), 0 passed in /var/www/html/playsms/plugin/themes/common/fn.php on line 23 and exactly 1 expected in /var/www/html/playsms/plugin/core/themes/fn.php:39\nStack trace:\n#0 /var/www/html/playsms/plugin/themes/common/fn.php(23): themes_submenu()\n#1 /var/www/html/playsms/lib/fn_core.php(192): common_hook_themes_apply('<table width='1...')\n#2 /var/www/html/playsms/plugin/core/themes/fn.php(32): core_hook('common', 'themes_apply', Array)\n#3 /var/www/html/playsms/inc/app/main.php(39): themes_apply('<table width='1...')\n#4 /var/www/html/playsms/index.php(34): include('/var/www/html/p...')\n#5 {main}\n  thrown in /var/www/html/playsms/plugin/core/themes/fn.php on line 39

I have:
Centos 7.5 x64
Apache 2.4.33
php php-mysql php-cli php-mbstring php-gb php-gettext (all is have 7.2.6 version)
First, I have mysql version 5.7.22 and upgrade it to 8.0.11

**Comment by MAPIIIAJI** [comment]
I successful install playSMS. And I understand that if install php with version 7.1 and higher and if mysql version will be 8.xx, playsms do not work properly and appear blank page on browser. Please release new version playsms that correct this problems. It is primarily refer to security. Thank you in advance.

**Comment by antonraharja** [comment]
fix https://github.com/antonraharja/playSMS/commit/ef8cc0d27fea5eeed077c2218d07739aec2c475f
