### ISSUE TITLE
PlaySMS don’t save sended masasges in “My sent messages” and “All sent messages”

### ISSUE THREAD

**Issue by MAPIIIAJI** [antonraharja/playSMS#574]
I have installed PlaySMS on CentOS and I have PHP 7.2.6, MySL 8.0.11 and Apache 2.4.33 and GAMMU.
SMSs perfectly sends to recipient but send massages don’t saves to Reports -> My sent messages. Please help me please. Thank you in advance.
![aaa](https://user-images.githubusercontent.com/35526267/41705726-4cc26eb6-7553-11e8-9f9b-cb1ff19ff7b6.jpg)

**Comment by antonraharja** [comment]
please ask question in forum
