### ISSUE TITLE
Mordern Admin Panel

### ISSUE THREAD

**Issue by xianx** [antonraharja/playSMS#575]
Play SMS is Great! I am now using it on my Kubernetes Cluster. But the Theme of PaySMS is dull. My Idea is to build a modern Admin Theme of PlaySMS.  There are lots of admin theme out there. I have found some of the best

techtun.es/lKtzZV
techtun.es/jr5YqB
techtun.es/Xs8vgP
techtun.es/sKJR77
techtun.es/LolQNV
techtun.es/RSU4mG
techtun.es/ULWuP6
techtun.es/ZBjEUj

It can be develop by own. Current play SMS theme is very dull and is not so modern.

**Comment by antonraharja** [comment]
not interested to work on this, for now. please discuss in forum instead
