### ISSUE TITLE
Playsms show mix content error over ssl

### ISSUE THREAD

**Issue by xianx** [antonraharja/playSMS#577]
I have install Playsms successfully over http. but when ever I am switching to https over ssl, Playsms showing mixed content error and css and js files are not loading https://techtun.es/0LzydI .

When looking in the source on browser I see there is double slash after each domain and http instead of https. It seams http is hard coded in the php source of Playsms see the screenshot https://techtun.es/ui9QBC

how to solve?

**Comment by antonraharja** [comment]
Have you set to use https from config.php ?
