### ISSUE TITLE
How to remove index.php from url?

### ISSUE THREAD

**Issue by xianx** [antonraharja/playSMS#578]
I have successfully install playsms. But want to remove index.php from url like https://demo.playsms.org/app=main&inc=core_welcome

I am using php-fmp+nginx

How can I do that?

**Comment by antonraharja** [comment]
Please do not post question in issue page, use forum instead

**Comment by xianx** [comment]
okay I will next time. but please provide a solution.

**Comment by xianx** [comment]
is it possible?
