### ISSUE TITLE
Fail to load main config from registry

### ISSUE THREAD

**Issue by nobicycle** [antonraharja/playSMS#591]
Hello and thanks for playSMS.

I have PlaySMS running with no errors in logs, systemctl status green etcetera, but when opening the web page I get:

> Fail to load main config from registry

I tested under php 7.2 and 7.3
There is no error in nginx log.

**Environment**
[me@tower ~]$ php-fpm -v
PHP 7.3.7 (fpm-fcgi) (built: Jul  3 2019 13:55:48)
[me@tower ~]$ php-fpm72 -v
PHP 7.2.17 (fpm-fcgi) (built: Jul  6 2019 17:19:43)

Best wishes

**Comment by antonraharja** [comment]
Please continue in forum.
