### ISSUE TITLE
Can't set "Send to" in "Compose message" page

### ISSUE THREAD

**Issue by pokapow** [antonraharja/playSMS#595]
I installed playSMS from github master following the install steps.

I can't chose phone number or contact to the form to send message.

![Capture du 2019-12-11 21-05-32](https://user-images.githubusercontent.com/30467320/70656370-40eb0580-1c5a-11ea-9616-47789bf5bc75.png)

I test with several user in phonebook, with phone number directly, without "@", always the same error  "Loading failed"

**Comment by skeeso** [comment]
Hi Anton. May I ask what is the fix for this? I am already running in https set to true but still contacts are not loading. Thanks.
