### ISSUE TITLE
Bug! Firewall not work properly!

### ISSUE THREAD

**Issue by wijde** [antonraharja/playSMS#599]
Firewall does not block traffic! When binding the admin account to the ip address 0.0.0.0 by logic with the admin account, it should not be possible to authenticate.

![Screenshot_20200121_104311](https://user-images.githubusercontent.com/35526267/73133750-f3322d00-404e-11ea-9b8c-c40b1d959c12.png)

Despite the fact that login from any addresses is blocked, authentication can be done using the admin account

And even this approach does not work

![Screenshot_20200121_123519](https://user-images.githubusercontent.com/35526267/73133763-2379cb80-404f-11ea-846c-19cd1a0b3882.png)

Dear Anton, please correct this moment.
Thanks in advance.

Respectfully,
Jamshid Tursunov

**Comment by antonraharja** [comment]
this is not a bug, current Firewall plugin can only block by IP, it is used for autoblock continues fail logins
