### ISSUE TITLE
404 not found 

### ISSUE THREAD

**Issue by zouhirmahjoubi** [antonraharja/playSMS#601]
![10](https://user-images.githubusercontent.com/55251855/73796276-1b3b3200-47ad-11ea-8c83-dc970f334a6e.PNG)
![11](https://user-images.githubusercontent.com/55251855/73796288-1e362280-47ad-11ea-964e-9a8b889eee0d.PNG)

**Comment by antonraharja** [comment]
you should setup your server to point to you playSMS web files. please post in forum. thanks.
