### ISSUE TITLE
small typo in playsms.sql

### ISSUE THREAD

**Issue by joshebosh** [antonraharja/playSMS#604]
When doing this command:

`cat /usr/src/playSMS.git/db/playsms.sql | mysql -u root -p playsms`

was getting error:

> ERROR 1136 (21S01): Column count doesn't match value count at row 1

Upon looking at line 1427:

`INSERT INTO `playsms_tblUser` VALUES (0,0,1,2,0,'admin','21232f297a57a5a743894a0e4a801fc3','',0,'127.0.0.1, 192.168.*.*','Administrator','+62000000000','noreply@playsms.org','playSMS','@admin','','','',82,'',0.000,0.000,'','en_US',0,1,1,'',1,0,0,0,'','',0);`

it looks like a column value `,''` was missing here `'21232f297a57a5a743894a0e4a801fc3','',0`
so i adjust to `'21232f297a57a5a743894a0e4a801fc3','','',0`

now the command works, looks like everything is aligned properly... column and data alignment looks proper... the country code 82 and language module en_US there after are in proper columns so i assume i've made the correct edit

thanks

**Comment by antonraharja** [comment]
its the master branch you're testing I suppose, yes its missing that, I added 1 column `salt`, thx
