### ISSUE TITLE
env vars - docker playsms connect to an existing mysql server

### ISSUE THREAD

**Issue by darrylsepeda** [antonraharja/playSMS#612]
Hi Mr Anton,

I tried to use PlaySMS in Docker and realised it is using port 3306.
Currently I have MariaDB running on my Docker machine for other purpose, I want to use the same MariaDB for PlaySMS instead of PlaySMS docker container have its own mysql server.

Is there any environment variables that I can use to make PlaySMS connect to other docker container?

**Comment by antonraharja** [comment]
Please continue in forum.
