### ISSUE TITLE
Scheduling message issue

### ISSUE THREAD

**Issue by fode-intc** [antonraharja/playSMS#614]
Hello, I have a problem with the scheduling of sms, when I schedule an sms at the time of sending there is an error which occurs at the saving queue. I've done a lot of research but can't seem to fix it.
I try normal sending it’s working well and schedule with normal sending it’s also working.

It’s only << scheduling message >> is not working.

Thank You for your help 

The lot is :

- - 2020-11-03 07:00:59 PID5fa00810366d6 fode L2 schedule_hook_playsmsd # sendsms uid:4 schedule_id:1 id:2 rule:0 schedule:[2020-11-03 07:00:00] scheduled:[2020-11-03 07:00:59]
- - 2020-11-03 07:00:59 PID5fa00810366d6 fode L2 sendsms # start uid:4 sender_id:[SMS] smsc:[]
- - 2020-11-03 07:00:59 PID5fa00810366d6 fode L3 sendsms # maxlen:459 footerlen:0 footer:[] msglen:24 message:[Scheu c'est pour le test]
- - 2020-11-03 07:00:59 PID5fa00810366d6 fode L2 sendsms_queue_create # saving queue_code:d5d4cd32183c78402d137255d479d96a src:SMS scheduled:2020-11-03 07:00:59
- - 2020-11-03 07:00:59 PID5fa00810366d6 fode L2 sendsms # fail to finalize queue creation, exit immediately

This message is always coming and scheduling sms is not sending.

**Comment by antonraharja** [comment]
please continue in forum
